### ISSUE TITLE
Remove Sans from Bootstrap documentation

### ISSUE THREAD

**Issue by akslay** [az-digital/arizona-bootstrap#245]
## Problem/Motivation
Sans is no longer an option with the change to Proxima Nova. We should remove it from the Bootstrap documentation (https://digital.arizona.edu/arizona-bootstrap/docs/2.0/utilities/text/#sans) and probably also remove it as a utilize class from the SCSS. 

The sans class doesn't work anyway (since we switched to Proxima Nova) so it looks like regular text in the documentation.
<img width="477" alt="Screen Shot 2021-03-23 at 9 33 51 AM" src="https://user-images.githubusercontent.com/52931751/112182842-e493c700-8bba-11eb-933b-fd14d8dbca57.png">

**Comment by smayden** [comment]
@mmunro-ltrr I noticed that you made a commit on this ticket back in March. Were you planning additional work on this?

https://github.com/az-digital/arizona-bootstrap/commit/677764b223679855add012943cf4e1fd47db7dfb

**Comment by mmunro-ltrr** [comment]
@smayden : I don't think there _is_ any additional work to do on this. The commit closed Issue #245, and was merged as part of the Jekyll to Hugo refactoring (at least, when I now search for the string `text-sans`, I can't find it anywhere in the repository). So it should be safe just to manually close the issue here.
