### ISSUE TITLE
Add gradient-title class

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/arizona-bootstrap#493]
## Motivation
I want to enhance my titles - connected to card updates.

## Proposed Resolution
Add new class and documentation
```
.gradient-title {
    background-image: linear-gradient(180deg, transparent, black);
    padding: 8rem 1.25rem 1.25rem 1.25rem;
    color: #ffffff;
}
```

### Describe alternatives you've considered
Padding of 8 rem is achievable with pt-10 class, but we do not have spacing classes to match 1.25rem which is the set padding of cards.

## Additional context
Blocks https://github.com/az-digital/az_quickstart/issues/1672

**Comment by akslay** [comment]
My thoughts since I will be out of the office when we are working on this:

- In general, I would rather break out the styles into two separate classes: `.bg-gradient-black` (naming convention will set the stage for other color options), which would include the gradient style and the fallback accessible text color by [leveraging what's we added to Bootstrap](https://github.com/az-digital/arizona-bootstrap/blob/4884de6bda2c7524bd768046bbd40560cd4519c2/scss/_mixins.scss#L29). Should probably [add them here](https://github.com/az-digital/arizona-bootstrap/blob/4884de6bda2c7524bd768046bbd40560cd4519c2/scss/_custom-variables.scss#L52) like we did for the transparent background colors.
- Add padding as a separate utility class that is probably specific to the Card use case? You mentioned the padding is more specific to cards/card-body and doesn't match what's available in our padding utilities. So maybe include it in the [Utilities section of the Card documentation](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/card/#using-utilities), and name it `.card-title .card-title-spacer-top` (or something along those lines). Basically just a class that's intuitive as to the style/function it's providing.

**Comment by danahertzberg** [comment]
@akslay I love it. What if the card padding utility was something like `p-card`?

**Comment by akslay** [comment]
@danahertzberg I like the idea of adding other variants to match the way we currently use padding utilities. So `.pt-card-lg`...etc. Would make it easier to style the gradient card as well on all breakpoints (i.e., probably don't want as much spacing on mobile).

**Comment by bberndt-uaz** [comment]
@danahertzberg Just so I understand the motivation behind this issue, is it intended to make the background gradient style available only for Quickstart cards or for any element that site builders wish to use it on?

**Comment by danahertzberg** [comment]
> @danahertzberg Just so I understand the motivation behind this issue, is it intended to make the background gradient style available only for Quickstart cards or for any element that site builders wish to use it on?

@bberndt-uaz The intent is to have it available in Bootstrap so it can be used anywhere and in combination with other utility classes.
