### ISSUE TITLE
The Docker-based build environment for CI and local development is unstable.

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/arizona-bootstrap#73]
## What is the problem that we want to solve?
The general-purpose Docker image used in the builds needs several additional steps that are slow and can be unreliable, particularly for `npm install`. We should investigate whether derived temporary Docker containers work around this for both local development and GitHub Actions, or whether GitHub Actions can handle the CI aspect, with more work being needed for local development.

## Conditions of satisfaction.         
- [ ] *Either* a proof-of-concept improved Docker-based environment for CI and local dev.
- [ ] *Or* a GitHub Actions-specific improvement proof-of-concept.
- [ ] An estimate of time and effort is provided for the recommendation.

**Comment by mmunro-ltrr** [comment]
There's been some progress with this, but I'm contemplating using symbolic links to stitch everything together. Remembering the problems we were having with az-quickstart, I'm assuming the links can't be exposed in anything that's exposed from the container to the host system, but if the links are inside the container, will that break some of the file change monitoring?

**Comment by tadean** [comment]
From what I've seen so far, as long as the symbolic links are hidden inside the container and aren't on a docker volume that's shared to the host, they seem to function as expected - most of the strange behaviors we saw in az-quickstart are related to eccentric behavior in how composer treats custom repositories rather than issues with the links themselves.

In regards to file-change monitoring, it's possible to get that working, some of the discussion [here](https://github.com/docker/for-mac/issues/2216) is useful.
